services:
  web:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      NODE_ENV: development
    command: npm run dev

  test:
    build:
      context: ./client
    volumes:
      - ./client:/app
    environment:
      NODE_ENV: development
    command: npm run test
