version: "3.8"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run dev

  frontend-test:
    build:
      context: ./client
      dockerfile: Dockerfile.test
    volumes:
      - ./client:/usr/src/app
    command: npm run test
