# Use the official Python image as the base
FROM python:3.8-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /app

# Assuming the solution folder is correctly relative to the Dockerfile context set in docker-compose.yml
COPY ./solution/server/requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy the server and tests code
COPY ./solution/server/ /app/server/
COPY ./tests/ /app/tests/

# Install additional dependencies for testing
RUN pip install --no-cache-dir pytest

# Set environment variables for testing
ENV DATABASE_URL=postgresql://postgres:password@db/postgres

# Command to run tests
CMD ["pytest", "/app/tests/test_main.py"]
