

services:
  backend:
    build: ./solution/server
    ports:
      - "8000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Needed to run Docker inside Docker
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./solution/client
    ports:
      - "3000:3000"
